# Miscellaneous
analytics: UA-153785985-2
favicon: /favicon.png
twitter: https://twitter.com/leo_velarde_
gmail: mailto:hi@leovelarde.com
github: https://github.com/aguacatevelarde
facebook:
instagram:
linkedin: https://br.linkedin.com/in/codermarcos
youtube:
whatsapp: